// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotenPro.Api.Data;

#nullable disable

namespace NotenPro.Api.Migrations
{
    [DbContext(typeof(NotenProDbContext))]
    [Migration("20251211091126_AddEarlyWarningStuff")]
    partial class AddEarlyWarningStuff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NotenPro.Api.Data.Entities.ClassEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassTeacherId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_teacher_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassTeacherId");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("classes");

                    b.HasData(
                        new
                        {
                            Id = "4ed42a29-bb73-4d1a-8a34-f0463a54098c",
                            ClassTeacherId = "87a934f4-1428-47aa-9368-bdbade74b9ec",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 575, DateTimeKind.Utc).AddTicks(7924),
                            Name = "5AHIT",
                            SchoolId = "b47f684d-6000-42cf-ad82-b5f8d36fde9e",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 575, DateTimeKind.Utc).AddTicks(8231)
                        },
                        new
                        {
                            Id = "b107a15b-ad5e-43cb-843f-d5ebedb48bd0",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 575, DateTimeKind.Utc).AddTicks(8535),
                            Name = "5BHIT",
                            SchoolId = "b47f684d-6000-42cf-ad82-b5f8d36fde9e",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 575, DateTimeKind.Utc).AddTicks(8535)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.EarlyWarningEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentAverage")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("current_average");

                    b.Property<bool>("IsSent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_sent");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("StudentId", "SubjectId", "CreatedAt");

                    b.ToTable("early_warnings");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.GradeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("GradeValue")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("grade_value");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("max_points");

                    b.Property<int?>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("test_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("StudentId", "TestId")
                        .IsUnique();

                    b.ToTable("grades");

                    b.HasData(
                        new
                        {
                            Id = "e502cf32-72f6-43f1-9a95-3852798ddf1a",
                            Comment = "Sehr gute Leistung!",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 711, DateTimeKind.Utc).AddTicks(1420),
                            GradeValue = 2.00m,
                            MaxPoints = 100,
                            Points = 82,
                            Status = 0,
                            StudentId = "45ea76af-3cb3-4a3f-a1ae-69783105c971",
                            TestId = "d82d4ae1-4b46-4a7b-b6f4-4f3e1af74e64",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 711, DateTimeKind.Utc).AddTicks(1622)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.NotificationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("message");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("notifications");

                    b.HasData(
                        new
                        {
                            Id = "bc4b39cb-33a3-44ad-8351-ea5ba0c169a7",
                            IsRead = false,
                            Message = "Deine Note für 'Algebra Test 1' wurde eingetragen: 2.00 (Gut)",
                            Timestamp = new DateTime(2025, 12, 11, 9, 11, 25, 711, DateTimeKind.Utc).AddTicks(4109),
                            Title = "Neue Note verfügbar",
                            Type = 2,
                            UserId = "45ea76af-3cb3-4a3f-a1ae-69783105c971"
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SchoolEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("schools");

                    b.HasData(
                        new
                        {
                            Id = "b47f684d-6000-42cf-ad82-b5f8d36fde9e",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 303, DateTimeKind.Utc).AddTicks(4788),
                            Location = "Krems an der Donau",
                            Name = "HTL Krems",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 303, DateTimeKind.Utc).AddTicks(5036)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.StudentClassEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enrolled_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique();

                    b.ToTable("student_classes");

                    b.HasData(
                        new
                        {
                            Id = "5991c8ed-8000-4be9-a691-ce8f2f2aa0a4",
                            ClassId = "4ed42a29-bb73-4d1a-8a34-f0463a54098c",
                            EnrolledAt = new DateTime(2025, 12, 11, 9, 11, 25, 710, DateTimeKind.Utc).AddTicks(3778),
                            StudentId = "45ea76af-3cb3-4a3f-a1ae-69783105c971"
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SubjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("subjects");

                    b.HasData(
                        new
                        {
                            Id = "95733880-5dd3-41bd-92d3-b6690ab2edcf",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 576, DateTimeKind.Utc).AddTicks(1591),
                            Description = "Angewandte Mathematik",
                            IsActive = true,
                            Name = "Mathematik",
                            SchoolId = "b47f684d-6000-42cf-ad82-b5f8d36fde9e",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 576, DateTimeKind.Utc).AddTicks(1817)
                        },
                        new
                        {
                            Id = "21bdc7e3-d9a8-4da0-90dd-ba0fe964ab02",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 576, DateTimeKind.Utc).AddTicks(2037),
                            Description = "Deutsche Sprache und Literatur",
                            IsActive = true,
                            Name = "Deutsch",
                            SchoolId = "b47f684d-6000-42cf-ad82-b5f8d36fde9e",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 576, DateTimeKind.Utc).AddTicks(2043)
                        },
                        new
                        {
                            Id = "fa849cb8-770b-4944-b7a0-683b1dc2c680",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 576, DateTimeKind.Utc).AddTicks(2047),
                            Description = "English Language",
                            IsActive = true,
                            Name = "Englisch",
                            SchoolId = "b47f684d-6000-42cf-ad82-b5f8d36fde9e",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 576, DateTimeKind.Utc).AddTicks(2047)
                        },
                        new
                        {
                            Id = "390c0f0b-c57f-4cba-8229-82e0d3c670f8",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 576, DateTimeKind.Utc).AddTicks(2057),
                            Description = "Software Engineering",
                            IsActive = true,
                            Name = "Programmieren",
                            SchoolId = "b47f684d-6000-42cf-ad82-b5f8d36fde9e",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 576, DateTimeKind.Utc).AddTicks(2057)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TeacherSubjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "SubjectId")
                        .IsUnique();

                    b.ToTable("teacher_subjects");

                    b.HasData(
                        new
                        {
                            Id = "91c77a66-2582-425c-9070-4f4c4869bdc9",
                            AssignedAt = new DateTime(2025, 12, 11, 9, 11, 25, 576, DateTimeKind.Utc).AddTicks(3643),
                            SubjectId = "95733880-5dd3-41bd-92d3-b6690ab2edcf",
                            TeacherId = "87a934f4-1428-47aa-9368-bdbade74b9ec"
                        },
                        new
                        {
                            Id = "a69cfaf5-c828-47d6-ae0a-728c19f2670d",
                            AssignedAt = new DateTime(2025, 12, 11, 9, 11, 25, 576, DateTimeKind.Utc).AddTicks(3879),
                            SubjectId = "390c0f0b-c57f-4cba-8229-82e0d3c670f8",
                            TeacherId = "87a934f4-1428-47aa-9368-bdbade74b9ec"
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("max_points");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("ClassId", "Date");

                    b.ToTable("tests");

                    b.HasData(
                        new
                        {
                            Id = "d82d4ae1-4b46-4a7b-b6f4-4f3e1af74e64",
                            ClassId = "4ed42a29-bb73-4d1a-8a34-f0463a54098c",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 710, DateTimeKind.Utc).AddTicks(7371),
                            Date = new DateTime(2025, 12, 4, 9, 11, 25, 710, DateTimeKind.Utc).AddTicks(6441),
                            Description = "Lineare Gleichungen und Funktionen",
                            MaxPoints = 100,
                            Name = "Algebra Test 1",
                            SubjectId = "95733880-5dd3-41bd-92d3-b6690ab2edcf",
                            TeacherId = "87a934f4-1428-47aa-9368-bdbade74b9ec",
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 710, DateTimeKind.Utc).AddTicks(7577)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("SchoolId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = "2984991f-7da0-445f-bdfb-b897226c01a6",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 302, DateTimeKind.Utc).AddTicks(4502),
                            Email = "sysadmin@notenpro.at",
                            IsActive = true,
                            Name = "System Administrator",
                            PasswordHash = "$2a$11$ukrZFKs2IgrERRgyXArgp.yqEd0y5uilTzhpF24SpKe.vM09.B5Oy",
                            Role = 3,
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 302, DateTimeKind.Utc).AddTicks(4780)
                        },
                        new
                        {
                            Id = "01ff43a6-7484-4c01-8a98-a867baae0c51",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 439, DateTimeKind.Utc).AddTicks(6709),
                            Email = "admin@htl-krems.ac.at",
                            IsActive = true,
                            Name = "HTL Admin",
                            PasswordHash = "$2a$11$nuXY69n/os/HJWum6Kbo6.Vm0eKbgPQpN60QLvwepKiFLhidK3r1S",
                            Role = 2,
                            SchoolId = "b47f684d-6000-42cf-ad82-b5f8d36fde9e",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 439, DateTimeKind.Utc).AddTicks(6713)
                        },
                        new
                        {
                            Id = "87a934f4-1428-47aa-9368-bdbade74b9ec",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 575, DateTimeKind.Utc).AddTicks(3747),
                            Email = "maria.schmidt@htl-krems.ac.at",
                            IsActive = true,
                            Name = "Prof. Maria Schmidt",
                            PasswordHash = "$2a$11$.zs56wZ0vf4StP5.aBd.hOquGA2IfYSXMgrx42/fWwkvw/uWeMS4.",
                            Role = 1,
                            SchoolId = "b47f684d-6000-42cf-ad82-b5f8d36fde9e",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 575, DateTimeKind.Utc).AddTicks(3755)
                        },
                        new
                        {
                            Id = "45ea76af-3cb3-4a3f-a1ae-69783105c971",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 710, DateTimeKind.Utc).AddTicks(1093),
                            Email = "max.mustermann@students.htl-krems.ac.at",
                            IsActive = true,
                            Name = "Max Mustermann",
                            PasswordHash = "$2a$11$SGwN.k5qbzPv3/9HaFEe3O9mgJnz5OZzdxez3/TVzJBRQPEw4aD7K",
                            Role = 0,
                            SchoolId = "b47f684d-6000-42cf-ad82-b5f8d36fde9e",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 25, 710, DateTimeKind.Utc).AddTicks(1096)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.ClassEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "ClassTeacher")
                        .WithMany()
                        .HasForeignKey("ClassTeacherId");

                    b.HasOne("NotenPro.Api.Data.Entities.SchoolEntity", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassTeacher");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.EarlyWarningEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.SubjectEntity", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.GradeEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.TestEntity", "Test")
                        .WithMany("Grades")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.NotificationEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.StudentClassEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.ClassEntity", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SubjectEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.SchoolEntity", "School")
                        .WithMany("Subjects")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TeacherSubjectEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.SubjectEntity", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TestEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.ClassEntity", "Class")
                        .WithMany("Tests")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.SubjectEntity", "Subject")
                        .WithMany("Tests")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Teacher")
                        .WithMany("CreatedTests")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.SchoolEntity", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.ClassEntity", b =>
                {
                    b.Navigation("StudentClasses");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SchoolEntity", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SubjectEntity", b =>
                {
                    b.Navigation("TeacherSubjects");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TestEntity", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("CreatedTests");

                    b.Navigation("Grades");

                    b.Navigation("Notifications");

                    b.Navigation("StudentClasses");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
