// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotenPro.Api.Data;

#nullable disable

namespace NotenPro.Api.Migrations
{
    [DbContext(typeof(NotenProDbContext))]
    [Migration("20260113092734_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NotenPro.Api.Data.Entities.ClassEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassTeacherId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_teacher_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassTeacherId");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("classes");

                    b.HasData(
                        new
                        {
                            Id = "b47ddd1b-48e3-45b0-ad11-3a817402e00c",
                            ClassTeacherId = "ed4c5c9f-c09b-4424-987f-8782f828c07c",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 312, DateTimeKind.Utc).AddTicks(6065),
                            Name = "5AHIT",
                            SchoolId = "db717465-da54-417d-bcf0-9867870774ba",
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 312, DateTimeKind.Utc).AddTicks(6789)
                        },
                        new
                        {
                            Id = "5019655e-4dbc-4f5e-9e0a-85eb10161f07",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 312, DateTimeKind.Utc).AddTicks(7477),
                            Name = "5BHIT",
                            SchoolId = "db717465-da54-417d-bcf0-9867870774ba",
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 312, DateTimeKind.Utc).AddTicks(7478)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.EarlyWarningEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentAverage")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("current_average");

                    b.Property<bool>("IsSent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_sent");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("StudentId", "SubjectId", "CreatedAt");

                    b.ToTable("early_warnings");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.GradeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("GradeValue")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("grade_value");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("max_points");

                    b.Property<int?>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("test_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("StudentId", "TestId")
                        .IsUnique();

                    b.ToTable("grades");

                    b.HasData(
                        new
                        {
                            Id = "99e19ab9-8774-4550-9564-cf2c0e49f7ea",
                            Comment = "Sehr gute Leistung!",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 550, DateTimeKind.Utc).AddTicks(625),
                            GradeValue = 2.00m,
                            MaxPoints = 100,
                            Points = 82,
                            Status = 0,
                            StudentId = "6db9373f-5d9f-4186-82dd-26282371f2b1",
                            TestId = "40cfe18f-35a2-425e-94b1-09c2a639c19d",
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 550, DateTimeKind.Utc).AddTicks(983)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.NotificationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("message");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("notifications");

                    b.HasData(
                        new
                        {
                            Id = "1fd7a96b-d211-46a9-ba6c-ef46fa3b1386",
                            IsRead = false,
                            Message = "Deine Note für 'Algebra Test 1' wurde eingetragen: 2.00 (Gut)",
                            Timestamp = new DateTime(2026, 1, 13, 9, 27, 32, 550, DateTimeKind.Utc).AddTicks(5092),
                            Title = "Neue Note verfügbar",
                            Type = 2,
                            UserId = "6db9373f-5d9f-4186-82dd-26282371f2b1"
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SchoolEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("schools");

                    b.HasData(
                        new
                        {
                            Id = "db717465-da54-417d-bcf0-9867870774ba",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 31, 828, DateTimeKind.Utc).AddTicks(1758),
                            Location = "Krems an der Donau",
                            Name = "HTL Krems",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 31, 828, DateTimeKind.Utc).AddTicks(2191)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.StudentClassEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enrolled_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique();

                    b.ToTable("student_classes");

                    b.HasData(
                        new
                        {
                            Id = "8791934c-8aed-4206-8dc7-d03ccf83248f",
                            ClassId = "b47ddd1b-48e3-45b0-ad11-3a817402e00c",
                            EnrolledAt = new DateTime(2026, 1, 13, 9, 27, 32, 548, DateTimeKind.Utc).AddTicks(7194),
                            StudentId = "6db9373f-5d9f-4186-82dd-26282371f2b1"
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SubjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("subjects");

                    b.HasData(
                        new
                        {
                            Id = "d357c9d0-5296-4d0d-af55-84e9da2f6518",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 313, DateTimeKind.Utc).AddTicks(4708),
                            Description = "Angewandte Mathematik",
                            IsActive = true,
                            Name = "Mathematik",
                            SchoolId = "db717465-da54-417d-bcf0-9867870774ba",
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 313, DateTimeKind.Utc).AddTicks(5348)
                        },
                        new
                        {
                            Id = "955d437b-25f0-41cc-a174-cb2c1331c3b3",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 313, DateTimeKind.Utc).AddTicks(6120),
                            Description = "Deutsche Sprache und Literatur",
                            IsActive = true,
                            Name = "Deutsch",
                            SchoolId = "db717465-da54-417d-bcf0-9867870774ba",
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 313, DateTimeKind.Utc).AddTicks(6133)
                        },
                        new
                        {
                            Id = "74ebf9f0-b178-4b80-a76e-56f744af573c",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 313, DateTimeKind.Utc).AddTicks(6147),
                            Description = "English Language",
                            IsActive = true,
                            Name = "Englisch",
                            SchoolId = "db717465-da54-417d-bcf0-9867870774ba",
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 313, DateTimeKind.Utc).AddTicks(6148)
                        },
                        new
                        {
                            Id = "9d9a2c26-0f79-490e-8db9-f1d750c05ece",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 313, DateTimeKind.Utc).AddTicks(6164),
                            Description = "Software Engineering",
                            IsActive = true,
                            Name = "Programmieren",
                            SchoolId = "db717465-da54-417d-bcf0-9867870774ba",
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 313, DateTimeKind.Utc).AddTicks(6165)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TeacherSubjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "SubjectId")
                        .IsUnique();

                    b.ToTable("teacher_subjects");

                    b.HasData(
                        new
                        {
                            Id = "5872c160-baa8-4532-a1a7-54038536050a",
                            AssignedAt = new DateTime(2026, 1, 13, 9, 27, 32, 314, DateTimeKind.Utc).AddTicks(998),
                            SubjectId = "d357c9d0-5296-4d0d-af55-84e9da2f6518",
                            TeacherId = "ed4c5c9f-c09b-4424-987f-8782f828c07c"
                        },
                        new
                        {
                            Id = "82a8cb90-676d-43b2-bece-0e7fb237e8db",
                            AssignedAt = new DateTime(2026, 1, 13, 9, 27, 32, 314, DateTimeKind.Utc).AddTicks(1676),
                            SubjectId = "9d9a2c26-0f79-490e-8db9-f1d750c05ece",
                            TeacherId = "ed4c5c9f-c09b-4424-987f-8782f828c07c"
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("max_points");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("ClassId", "Date");

                    b.ToTable("tests");

                    b.HasData(
                        new
                        {
                            Id = "40cfe18f-35a2-425e-94b1-09c2a639c19d",
                            ClassId = "b47ddd1b-48e3-45b0-ad11-3a817402e00c",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 549, DateTimeKind.Utc).AddTicks(4178),
                            Date = new DateTime(2026, 1, 6, 9, 27, 32, 549, DateTimeKind.Utc).AddTicks(2545),
                            Description = "Lineare Gleichungen und Funktionen",
                            MaxPoints = 100,
                            Name = "Algebra Test 1",
                            SubjectId = "d357c9d0-5296-4d0d-af55-84e9da2f6518",
                            TeacherId = "ed4c5c9f-c09b-4424-987f-8782f828c07c",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 549, DateTimeKind.Utc).AddTicks(4555)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("SchoolId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = "aa63eeaf-7628-44d5-8c41-0868d195fef6",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 31, 826, DateTimeKind.Utc).AddTicks(4489),
                            Email = "sysadmin@notenpro.at",
                            ExternalId = "",
                            IsActive = true,
                            Name = "System Administrator",
                            PasswordHash = "$2a$11$oXWxpJJMr9h8zQFjqtG.Vu7MTWDnr0gPiPe79u.2d3HqR.AjmSN.u",
                            Role = 3,
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 31, 826, DateTimeKind.Utc).AddTicks(5087)
                        },
                        new
                        {
                            Id = "1a57c275-b107-4442-a8ae-513faa74143d",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 75, DateTimeKind.Utc).AddTicks(2406),
                            Email = "admin@htl-krems.ac.at",
                            ExternalId = "",
                            IsActive = true,
                            Name = "HTL Admin",
                            PasswordHash = "$2a$11$qoxsf5L05CckULJjWJwMVu4ymj/xgerlus4BZJwmoTW9MVLdLOIwO",
                            Role = 2,
                            SchoolId = "db717465-da54-417d-bcf0-9867870774ba",
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 75, DateTimeKind.Utc).AddTicks(2412)
                        },
                        new
                        {
                            Id = "ed4c5c9f-c09b-4424-987f-8782f828c07c",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 311, DateTimeKind.Utc).AddTicks(7639),
                            Email = "maria.schmidt@htl-krems.ac.at",
                            ExternalId = "",
                            IsActive = true,
                            Name = "Prof. Maria Schmidt",
                            PasswordHash = "$2a$11$/Ky6muhpQPW600xVJCX9wumKKs2SNSFmGFxCRB48FyRlWH4QJ2IoW",
                            Role = 1,
                            SchoolId = "db717465-da54-417d-bcf0-9867870774ba",
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 311, DateTimeKind.Utc).AddTicks(7647)
                        },
                        new
                        {
                            Id = "6db9373f-5d9f-4186-82dd-26282371f2b1",
                            CreatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 548, DateTimeKind.Utc).AddTicks(2769),
                            Email = "max.mustermann@students.htl-krems.ac.at",
                            ExternalId = "",
                            IsActive = true,
                            Name = "Max Mustermann",
                            PasswordHash = "$2a$11$UbKyhg2CwTJZye21z.7OmO54XC/x06X5N7VELvAD5MAtV9AfGv4TW",
                            Role = 0,
                            SchoolId = "db717465-da54-417d-bcf0-9867870774ba",
                            UpdatedAt = new DateTime(2026, 1, 13, 9, 27, 32, 548, DateTimeKind.Utc).AddTicks(2772)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.ClassEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "ClassTeacher")
                        .WithMany()
                        .HasForeignKey("ClassTeacherId");

                    b.HasOne("NotenPro.Api.Data.Entities.SchoolEntity", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassTeacher");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.EarlyWarningEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.SubjectEntity", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.GradeEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.TestEntity", "Test")
                        .WithMany("Grades")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.NotificationEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.StudentClassEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.ClassEntity", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SubjectEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.SchoolEntity", "School")
                        .WithMany("Subjects")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TeacherSubjectEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.SubjectEntity", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TestEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.ClassEntity", "Class")
                        .WithMany("Tests")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.SubjectEntity", "Subject")
                        .WithMany("Tests")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Teacher")
                        .WithMany("CreatedTests")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.SchoolEntity", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.ClassEntity", b =>
                {
                    b.Navigation("StudentClasses");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SchoolEntity", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SubjectEntity", b =>
                {
                    b.Navigation("TeacherSubjects");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TestEntity", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("CreatedTests");

                    b.Navigation("Grades");

                    b.Navigation("Notifications");

                    b.Navigation("StudentClasses");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
