// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotenPro.Api.Data;

#nullable disable

namespace NotenPro.Api.Migrations
{
    [DbContext(typeof(NotenProDbContext))]
    partial class NotenProDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NotenPro.Api.Data.Entities.ClassEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassTeacherId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_teacher_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassTeacherId");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("classes");

                    b.HasData(
                        new
                        {
                            Id = "33a31a22-4070-4097-9c09-a9996c104509",
                            ClassTeacherId = "abbd0f05-349f-4e22-8427-dc126fcb6284",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(1573),
                            Name = "5AHIT",
                            SchoolId = "20fe3462-07c4-426d-91e0-033fd17d820a",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(1833)
                        },
                        new
                        {
                            Id = "7fee9762-3b89-4bd9-9f7b-250b493a5644",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(2090),
                            Name = "5BHIT",
                            SchoolId = "20fe3462-07c4-426d-91e0-033fd17d820a",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(2091)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.EarlyWarningEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentAverage")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("current_average");

                    b.Property<bool>("IsSent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_sent");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("StudentId", "SubjectId", "CreatedAt");

                    b.ToTable("early_warnings");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.GradeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("GradeValue")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("grade_value");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("max_points");

                    b.Property<int?>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("test_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("StudentId", "TestId")
                        .IsUnique();

                    b.ToTable("grades");

                    b.HasData(
                        new
                        {
                            Id = "03b24fcc-a1f2-4290-9982-b9b83c42ff1c",
                            Comment = "Sehr gute Leistung!",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 867, DateTimeKind.Utc).AddTicks(5507),
                            GradeValue = 2.00m,
                            MaxPoints = 100,
                            Points = 82,
                            Status = 0,
                            StudentId = "a6aaa29b-1db6-467a-ab28-4122bafc1061",
                            TestId = "fd537b2a-6625-4564-a75c-c3d0ca58c922",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 867, DateTimeKind.Utc).AddTicks(5738)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.NotificationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("message");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("notifications");

                    b.HasData(
                        new
                        {
                            Id = "6f3d8d40-4a04-4223-8a5e-73b01a3c936d",
                            IsRead = false,
                            Message = "Deine Note für 'Algebra Test 1' wurde eingetragen: 2.00 (Gut)",
                            Timestamp = new DateTime(2025, 12, 11, 9, 11, 44, 867, DateTimeKind.Utc).AddTicks(8727),
                            Title = "Neue Note verfügbar",
                            Type = 2,
                            UserId = "a6aaa29b-1db6-467a-ab28-4122bafc1061"
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SchoolEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("schools");

                    b.HasData(
                        new
                        {
                            Id = "20fe3462-07c4-426d-91e0-033fd17d820a",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 427, DateTimeKind.Utc).AddTicks(6150),
                            Location = "Krems an der Donau",
                            Name = "HTL Krems",
                            Status = "Active",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 427, DateTimeKind.Utc).AddTicks(6389)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.StudentClassEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enrolled_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique();

                    b.ToTable("student_classes");

                    b.HasData(
                        new
                        {
                            Id = "a6c342e3-c078-4d0e-9307-3ce3a08cb8e0",
                            ClassId = "33a31a22-4070-4097-9c09-a9996c104509",
                            EnrolledAt = new DateTime(2025, 12, 11, 9, 11, 44, 866, DateTimeKind.Utc).AddTicks(3519),
                            StudentId = "a6aaa29b-1db6-467a-ab28-4122bafc1061"
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SubjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("subjects");

                    b.HasData(
                        new
                        {
                            Id = "6c7dcb42-a1b2-4607-9e2d-95be7498b92c",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(4895),
                            Description = "Angewandte Mathematik",
                            IsActive = true,
                            Name = "Mathematik",
                            SchoolId = "20fe3462-07c4-426d-91e0-033fd17d820a",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(5123)
                        },
                        new
                        {
                            Id = "acd30c33-950a-48ba-8887-c41e4aeaf507",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(5617),
                            Description = "Deutsche Sprache und Literatur",
                            IsActive = true,
                            Name = "Deutsch",
                            SchoolId = "20fe3462-07c4-426d-91e0-033fd17d820a",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(5622)
                        },
                        new
                        {
                            Id = "675d7ccb-746e-4c55-9288-ccb1d14858d5",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(5625),
                            Description = "English Language",
                            IsActive = true,
                            Name = "Englisch",
                            SchoolId = "20fe3462-07c4-426d-91e0-033fd17d820a",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(5625)
                        },
                        new
                        {
                            Id = "94614d7e-c9d5-41da-b217-64bc4795d75f",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(5632),
                            Description = "Software Engineering",
                            IsActive = true,
                            Name = "Programmieren",
                            SchoolId = "20fe3462-07c4-426d-91e0-033fd17d820a",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(5632)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TeacherSubjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "SubjectId")
                        .IsUnique();

                    b.ToTable("teacher_subjects");

                    b.HasData(
                        new
                        {
                            Id = "9caaa60d-0e7b-4efd-bb0d-20f099271307",
                            AssignedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(7232),
                            SubjectId = "6c7dcb42-a1b2-4607-9e2d-95be7498b92c",
                            TeacherId = "abbd0f05-349f-4e22-8427-dc126fcb6284"
                        },
                        new
                        {
                            Id = "93f02d45-0845-4815-a2f8-84dd2a84b585",
                            AssignedAt = new DateTime(2025, 12, 11, 9, 11, 44, 711, DateTimeKind.Utc).AddTicks(7475),
                            SubjectId = "94614d7e-c9d5-41da-b217-64bc4795d75f",
                            TeacherId = "abbd0f05-349f-4e22-8427-dc126fcb6284"
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("max_points");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("ClassId", "Date");

                    b.ToTable("tests");

                    b.HasData(
                        new
                        {
                            Id = "fd537b2a-6625-4564-a75c-c3d0ca58c922",
                            ClassId = "33a31a22-4070-4097-9c09-a9996c104509",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 867, DateTimeKind.Utc).AddTicks(698),
                            Date = new DateTime(2025, 12, 4, 9, 11, 44, 866, DateTimeKind.Utc).AddTicks(8858),
                            Description = "Lineare Gleichungen und Funktionen",
                            MaxPoints = 100,
                            Name = "Algebra Test 1",
                            SubjectId = "6c7dcb42-a1b2-4607-9e2d-95be7498b92c",
                            TeacherId = "abbd0f05-349f-4e22-8427-dc126fcb6284",
                            Type = 0,
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 867, DateTimeKind.Utc).AddTicks(961)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("SchoolId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = "aaf3d1f8-0bc3-4197-bd48-1365f4d66fb2",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 426, DateTimeKind.Utc).AddTicks(6068),
                            Email = "sysadmin@notenpro.at",
                            IsActive = true,
                            Name = "System Administrator",
                            PasswordHash = "$2a$11$b5h2.aUW5UItWKz5Dyf71e3nZtHma4Dg4Lg5Hsvf/qa8FDisNkfSa",
                            Role = 3,
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 426, DateTimeKind.Utc).AddTicks(6335)
                        },
                        new
                        {
                            Id = "b90435c6-022f-4a1e-a06f-540b76f71aa9",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 566, DateTimeKind.Utc).AddTicks(8099),
                            Email = "admin@htl-krems.ac.at",
                            IsActive = true,
                            Name = "HTL Admin",
                            PasswordHash = "$2a$11$DnIOa0lBL4JwPA0f3tnzAeyRTq0U32nqacqo51GmooU9OmGj7X88O",
                            Role = 2,
                            SchoolId = "20fe3462-07c4-426d-91e0-033fd17d820a",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 566, DateTimeKind.Utc).AddTicks(8103)
                        },
                        new
                        {
                            Id = "abbd0f05-349f-4e22-8427-dc126fcb6284",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 710, DateTimeKind.Utc).AddTicks(7506),
                            Email = "maria.schmidt@htl-krems.ac.at",
                            IsActive = true,
                            Name = "Prof. Maria Schmidt",
                            PasswordHash = "$2a$11$ReT4loFQTLWa1BGtioZDdey3tmo8EhSiJJwfcieGm8m7oXIt1AG.W",
                            Role = 1,
                            SchoolId = "20fe3462-07c4-426d-91e0-033fd17d820a",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 710, DateTimeKind.Utc).AddTicks(7510)
                        },
                        new
                        {
                            Id = "a6aaa29b-1db6-467a-ab28-4122bafc1061",
                            CreatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 866, DateTimeKind.Utc).AddTicks(91),
                            Email = "max.mustermann@students.htl-krems.ac.at",
                            IsActive = true,
                            Name = "Max Mustermann",
                            PasswordHash = "$2a$11$SuDsEK4tYx2klDAjp.89culDtfaLhEtrJ9xg7abMs.njyDjcmIgCC",
                            Role = 0,
                            SchoolId = "20fe3462-07c4-426d-91e0-033fd17d820a",
                            UpdatedAt = new DateTime(2025, 12, 11, 9, 11, 44, 866, DateTimeKind.Utc).AddTicks(94)
                        });
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.ClassEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "ClassTeacher")
                        .WithMany()
                        .HasForeignKey("ClassTeacherId");

                    b.HasOne("NotenPro.Api.Data.Entities.SchoolEntity", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassTeacher");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.EarlyWarningEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.SubjectEntity", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.GradeEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.TestEntity", "Test")
                        .WithMany("Grades")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.NotificationEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.StudentClassEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.ClassEntity", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SubjectEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.SchoolEntity", "School")
                        .WithMany("Subjects")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TeacherSubjectEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.SubjectEntity", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TestEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.ClassEntity", "Class")
                        .WithMany("Tests")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.SubjectEntity", "Subject")
                        .WithMany("Tests")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Api.Data.Entities.UserEntity", "Teacher")
                        .WithMany("CreatedTests")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("NotenPro.Api.Data.Entities.SchoolEntity", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.ClassEntity", b =>
                {
                    b.Navigation("StudentClasses");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SchoolEntity", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.SubjectEntity", b =>
                {
                    b.Navigation("TeacherSubjects");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.TestEntity", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("NotenPro.Api.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("CreatedTests");

                    b.Navigation("Grades");

                    b.Navigation("Notifications");

                    b.Navigation("StudentClasses");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
