// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotenPro.Api.Data;

#nullable disable

namespace NotenPro.Api.Migrations
{
    [DbContext(typeof(NotenProDbContext))]
    partial class NotenProDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NotenPro.Domain.Entities.ClassEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassTeacherId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_teacher_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassTeacherId");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("classes");

                    b.HasData(
                        new
                        {
                            Id = "f064126f-70fb-413c-9609-daf1e25979b9",
                            ClassTeacherId = "72401289-ab71-4d04-bd16-e374bb7fc257",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(3312),
                            Name = "5AHIT",
                            SchoolId = "7ea2e317-112a-4673-967c-051882616f4e",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(3723)
                        },
                        new
                        {
                            Id = "1905611e-f2ae-4b79-bd61-5b7aa6244f64",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(4286),
                            Name = "5BHIT",
                            SchoolId = "7ea2e317-112a-4673-967c-051882616f4e",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(4286)
                        });
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.EarlyWarningEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentAverage")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("current_average");

                    b.Property<bool>("IsSent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_sent");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("StudentId", "SubjectId", "CreatedAt");

                    b.ToTable("early_warnings");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.GradeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("GradeValue")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("grade_value");

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("max_points");

                    b.Property<int?>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("test_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("StudentId", "TestId")
                        .IsUnique();

                    b.ToTable("grades");

                    b.HasData(
                        new
                        {
                            Id = "1fd5e77c-033e-48bf-8da5-fa923a04483a",
                            Comment = "Sehr gute Leistung!",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 998, DateTimeKind.Utc).AddTicks(5150),
                            GradeValue = 2.00m,
                            MaxPoints = 100,
                            Points = 82,
                            Status = 0,
                            StudentId = "faf52356-a0cf-4777-a518-ddefe7e20ffe",
                            TestId = "3cbcd1c7-884b-4fa3-b3a2-2d7a10fe3761",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 998, DateTimeKind.Utc).AddTicks(5425)
                        });
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.NotificationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("message");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("notifications");

                    b.HasData(
                        new
                        {
                            Id = "008874fa-ae31-4822-9e70-2a10ae71ecc6",
                            IsRead = false,
                            Message = "Deine Note für 'Algebra Test 1' wurde eingetragen: 2.00 (Gut)",
                            Timestamp = new DateTime(2026, 1, 16, 7, 18, 23, 998, DateTimeKind.Utc).AddTicks(8784),
                            Title = "Neue Note verfügbar",
                            Type = 2,
                            UserId = "faf52356-a0cf-4777-a518-ddefe7e20ffe"
                        });
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.SchoolEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("schools");

                    b.HasData(
                        new
                        {
                            Id = "7ea2e317-112a-4673-967c-051882616f4e",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 254, DateTimeKind.Utc).AddTicks(2931),
                            Location = "Krems an der Donau",
                            Name = "HTL Krems",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 254, DateTimeKind.Utc).AddTicks(3242)
                        });
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.StudentClassEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enrolled_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique();

                    b.ToTable("student_classes");

                    b.HasData(
                        new
                        {
                            Id = "e96ffab7-fab4-479a-8220-a3450621efc4",
                            ClassId = "f064126f-70fb-413c-9609-daf1e25979b9",
                            EnrolledAt = new DateTime(2026, 1, 16, 7, 18, 23, 997, DateTimeKind.Utc).AddTicks(4452),
                            StudentId = "faf52356-a0cf-4777-a518-ddefe7e20ffe"
                        });
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.SubjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Name");

                    b.ToTable("subjects");

                    b.HasData(
                        new
                        {
                            Id = "df3fbd45-39ed-4f13-b194-c64e2f55e291",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(7633),
                            Description = "Angewandte Mathematik",
                            IsActive = true,
                            Name = "Mathematik",
                            SchoolId = "7ea2e317-112a-4673-967c-051882616f4e",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(7929)
                        },
                        new
                        {
                            Id = "9eb7dfc3-93ad-4b71-ad8b-7bbbd9fb624f",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(8216),
                            Description = "Deutsche Sprache und Literatur",
                            IsActive = true,
                            Name = "Deutsch",
                            SchoolId = "7ea2e317-112a-4673-967c-051882616f4e",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(8222)
                        },
                        new
                        {
                            Id = "35e5d14a-ba00-49fb-ae47-6d752ba3ce88",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(8233),
                            Description = "English Language",
                            IsActive = true,
                            Name = "Englisch",
                            SchoolId = "7ea2e317-112a-4673-967c-051882616f4e",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(8233)
                        },
                        new
                        {
                            Id = "ec8dec77-ecbd-4031-a601-8dd72428e450",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(8264),
                            Description = "Software Engineering",
                            IsActive = true,
                            Name = "Programmieren",
                            SchoolId = "7ea2e317-112a-4673-967c-051882616f4e",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 822, DateTimeKind.Utc).AddTicks(8265)
                        });
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.TeacherSubjectEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "SubjectId")
                        .IsUnique();

                    b.ToTable("teacher_subjects");

                    b.HasData(
                        new
                        {
                            Id = "2f50b156-7bd4-4947-87f2-b019bb7aece9",
                            AssignedAt = new DateTime(2026, 1, 16, 7, 18, 23, 823, DateTimeKind.Utc).AddTicks(397),
                            SubjectId = "df3fbd45-39ed-4f13-b194-c64e2f55e291",
                            TeacherId = "72401289-ab71-4d04-bd16-e374bb7fc257"
                        },
                        new
                        {
                            Id = "c02492f4-7ca5-4d2b-93da-437877196886",
                            AssignedAt = new DateTime(2026, 1, 16, 7, 18, 23, 823, DateTimeKind.Utc).AddTicks(1049),
                            SubjectId = "ec8dec77-ecbd-4031-a601-8dd72428e450",
                            TeacherId = "72401289-ab71-4d04-bd16-e374bb7fc257"
                        });
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.TestEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("int")
                        .HasColumnName("max_points");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("subject_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("teacher_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("ClassId", "Date");

                    b.ToTable("tests");

                    b.HasData(
                        new
                        {
                            Id = "3cbcd1c7-884b-4fa3-b3a2-2d7a10fe3761",
                            ClassId = "f064126f-70fb-413c-9609-daf1e25979b9",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 998, DateTimeKind.Utc).AddTicks(67),
                            Date = new DateTime(2026, 1, 9, 7, 18, 23, 997, DateTimeKind.Utc).AddTicks(8723),
                            Description = "Lineare Gleichungen und Funktionen",
                            MaxPoints = 100,
                            Name = "Algebra Test 1",
                            SubjectId = "df3fbd45-39ed-4f13-b194-c64e2f55e291",
                            TeacherId = "72401289-ab71-4d04-bd16-e374bb7fc257",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 998, DateTimeKind.Utc).AddTicks(519)
                        });
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("SchoolId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("school_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = "cfcdd489-e0cf-4274-b579-ae1afc964d61",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 252, DateTimeKind.Utc).AddTicks(9499),
                            Email = "sysadmin@notenpro.at",
                            ExternalId = "",
                            IsActive = true,
                            Name = "System Administrator",
                            PasswordHash = "$2a$11$cwDTglpdkXqqno1ZmWuG6Ohx7wFEMEpQu3XQat.9HjSR.bgtG3oLa",
                            Role = 3,
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 252, DateTimeKind.Utc).AddTicks(9833)
                        },
                        new
                        {
                            Id = "7c11c4de-8754-4864-a1cc-d69be562fa72",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 649, DateTimeKind.Utc).AddTicks(5157),
                            Email = "admin@htl-krems.ac.at",
                            ExternalId = "",
                            IsActive = true,
                            Name = "HTL Admin",
                            PasswordHash = "$2a$11$VskBSIPXQ/2NrJUHdq4ujem620MWYwoLh2U4VyHkgj1fMgzCS4m7.",
                            Role = 2,
                            SchoolId = "7ea2e317-112a-4673-967c-051882616f4e",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 649, DateTimeKind.Utc).AddTicks(5161)
                        },
                        new
                        {
                            Id = "72401289-ab71-4d04-bd16-e374bb7fc257",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 821, DateTimeKind.Utc).AddTicks(9198),
                            Email = "maria.schmidt@htl-krems.ac.at",
                            ExternalId = "",
                            IsActive = true,
                            Name = "Prof. Maria Schmidt",
                            PasswordHash = "$2a$11$9lxohmpui3k7iidhkBtAOe0BLnpabBWBdR.wj9yK/ERXnPdTpw3LK",
                            Role = 1,
                            SchoolId = "7ea2e317-112a-4673-967c-051882616f4e",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 821, DateTimeKind.Utc).AddTicks(9202)
                        },
                        new
                        {
                            Id = "faf52356-a0cf-4777-a518-ddefe7e20ffe",
                            CreatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 997, DateTimeKind.Utc).AddTicks(1182),
                            Email = "max.mustermann@students.htl-krems.ac.at",
                            ExternalId = "",
                            IsActive = true,
                            Name = "Max Mustermann",
                            PasswordHash = "$2a$11$5bkWWWhflciyB5Ta90eLyedISlwTZtTa8FQWLRSlKC3zhii1UbqX.",
                            Role = 0,
                            SchoolId = "7ea2e317-112a-4673-967c-051882616f4e",
                            UpdatedAt = new DateTime(2026, 1, 16, 7, 18, 23, 997, DateTimeKind.Utc).AddTicks(1186)
                        });
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.ClassEntity", b =>
                {
                    b.HasOne("NotenPro.Domain.Entities.UserEntity", "ClassTeacher")
                        .WithMany()
                        .HasForeignKey("ClassTeacherId");

                    b.HasOne("NotenPro.Domain.Entities.SchoolEntity", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassTeacher");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.EarlyWarningEntity", b =>
                {
                    b.HasOne("NotenPro.Domain.Entities.UserEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Domain.Entities.SubjectEntity", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Domain.Entities.UserEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.GradeEntity", b =>
                {
                    b.HasOne("NotenPro.Domain.Entities.UserEntity", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Domain.Entities.TestEntity", "Test")
                        .WithMany("Grades")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.NotificationEntity", b =>
                {
                    b.HasOne("NotenPro.Domain.Entities.UserEntity", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.StudentClassEntity", b =>
                {
                    b.HasOne("NotenPro.Domain.Entities.ClassEntity", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Domain.Entities.UserEntity", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.SubjectEntity", b =>
                {
                    b.HasOne("NotenPro.Domain.Entities.SchoolEntity", "School")
                        .WithMany("Subjects")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.TeacherSubjectEntity", b =>
                {
                    b.HasOne("NotenPro.Domain.Entities.SubjectEntity", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Domain.Entities.UserEntity", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.TestEntity", b =>
                {
                    b.HasOne("NotenPro.Domain.Entities.ClassEntity", "Class")
                        .WithMany("Tests")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Domain.Entities.SubjectEntity", "Subject")
                        .WithMany("Tests")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotenPro.Domain.Entities.UserEntity", "Teacher")
                        .WithMany("CreatedTests")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.UserEntity", b =>
                {
                    b.HasOne("NotenPro.Domain.Entities.SchoolEntity", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId");

                    b.Navigation("School");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.ClassEntity", b =>
                {
                    b.Navigation("StudentClasses");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.SchoolEntity", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.SubjectEntity", b =>
                {
                    b.Navigation("TeacherSubjects");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.TestEntity", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("NotenPro.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("CreatedTests");

                    b.Navigation("Grades");

                    b.Navigation("Notifications");

                    b.Navigation("StudentClasses");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
