<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.9"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.9" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="9.0.9"/>
        <PackageReference Include="MudBlazor" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Pages\Admin\Audit.razor" />
      <_ContentIncludedByDefault Remove="Pages\Admin\Backups.razor" />
      <_ContentIncludedByDefault Remove="Pages\Admin\Classes.razor" />
      <_ContentIncludedByDefault Remove="Pages\Admin\Dashboard.razor" />
      <_ContentIncludedByDefault Remove="Pages\Admin\Maps.razor" />
      <_ContentIncludedByDefault Remove="Pages\Admin\Subjects.razor" />
      <_ContentIncludedByDefault Remove="Pages\Admin\Teachers.razor" />
      <_ContentIncludedByDefault Remove="Pages\Student\Dashboard.razor" />
      <_ContentIncludedByDefault Remove="Pages\Student\Grades.razor" />
      <_ContentIncludedByDefault Remove="Pages\Student\Notifications.razor" />
      <_ContentIncludedByDefault Remove="Pages\Teacher\Classes.razor" />
      <_ContentIncludedByDefault Remove="Pages\Teacher\Dashboard.razor" />
      <_ContentIncludedByDefault Remove="Pages\Teacher\GradeEntry.razor" />
      <_ContentIncludedByDefault Remove="Pages\Teacher\Tests.razor" />
      <_ContentIncludedByDefault Remove="Pages\Teacher\Warnings.razor" />
    </ItemGroup>

</Project>
